name: protection
on:
  create:
    
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: |
      echo "'{ \
  "required_status_checks": { \
    "strict": true, \
    "contexts": ["contexts"] \
  }, \
  "enforce_admins": true, \
  "required_pull_request_reviews": { \
    "dismissal_restrictions": { \
      "users": ["users"], \
      "teams": ["teams"] \
    }, \
    "dismiss_stale_reviews": false, \
    "require_code_owner_reviews": false, \
    "required_approving_review_count": 1 \
  }, \
  "restrictions": { \
    "users": ["users"], \
    "teams": ["teams"], \
    "apps": ["apps"] \
  } \
}'" >/tmp/config-branch-rules
      gh api --method PUT repos/$OWNER/$REPO/branches/main/protection --input /tmp/config-branch-rules  >/dev/null
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.event.repository.repo }}
          OWNER: ${{ github.event.repository.owner }}
          PARAMS: $
