name: protection
on:
  create:
    
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
        run: gh api --method PUT repos/$OWNER/$REPO/branches/main/protection --input ./config-branch-rules  >/dev/null
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.event.repository.repo }}
          OWNER: ${{ github.event.repository.owner }}
