name: protection
on:
  create:
    
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: gh api --method PUT repos/$ROWNER/$REPO/branches/main/protection --input ./config-branch-rules
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.event.repository.repo }}
          ROWNER: ${{ github.event.repository.owner }}
